# Módulos de `Python`: `numpy`

## `numpy`

`numpy` es un módulo para trabajar con arrays, que son un tipo de lista, lo que mucho más rápidos de procesar.

El objeto array de `numpy` recibe el nombre de `ndarray`. Este tipo de dato es muy usado en el mundo de la ciencia de datos, donde la velocidad y los recursos son de gran importancia.

In [ ]:
import numpy as np

Podemos comprobar la versión de `numpy` con la siguiente línea de código

In [ ]:
print(np.__version__)

1.19.5


#### Creando arrays

Para crear un `ndarray` usamos el método `.array()`.

Lo podemos hacer a partir de una lista:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


O bien, a partir de una tupla:

In [ ]:
b = np.array((1, 2, 3, 4, 5, 6, 7))
print(b)

[1 2 3 4 5 6 7]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


### Dimensiones de un array

La dimensión de una array viene dada por el nivel de profundidad de éste.

Para saber la dimensión de un array, podemos usar la propiedad `.ndim`

**¡Cuidado!**. En las versiones actuales de `Python`, si creamos un array $n$-dimensional, entonces todos los arrays de dimensión fija $m < n$, deben contener el mismo número de elementos. Es decir, si creamos un array de 4 dimensiones, todos los arrays de 3 dimensiones deben tener el mismo número de elementos; por su parte, todos los arrays de 2 dimensiones, deben tener el mismo número de elementos; y lo mismo para los arrays 1-dimensionales. Esto se debe a que en caso contrario, el atributo `.shape` que veremos a continuación no tendría sentido.

#### Arrays 0-dimensionales

Son los arrays constantes:

In [ ]:
d0 = np.array(77)
d0.ndim

0

#### Arrays 1-dimensionales

Son los arrays con un solo nivel de profundidad

In [ ]:
d1 = np.array([-1, 0, 1])
d1.ndim

1

#### Arrays 2-dimensionales

Son los arrays que tienen por elementos arrays unidimensionales:

In [ ]:
d2 = np.array([[-3, -2], [-1, 0]])
d2.ndim

2

#### Arrays 3-dimensionales

Son los arrays que tinenen por elementos arrays bidimensionales:

In [ ]:
d3 = np.array([[[1, 2, 3, 4], [4, 3, 2, 1]], [[1, 0, 1, 0], [-1, 1, -1, 1]]])
d3.ndim

3

#### Arrays multidimensionales

Un array puede tener cualquier número finito de dimensiones.

A la hora de crear un `ndarray`, podemos indicar como parámetro el número de dimensiones que queramos que tenga dicho array con el argumento `ndmin`

In [ ]:
a = np.array([-2, -1, 0, 1, 2], ndmin = 7)
print("El array a tiene {} dimensiones".format(a.ndim))
print(a)

El array a tiene 7 dimensiones
[[[[[[[-2 -1  0  1  2]]]]]]]


### `Shape` de un array

**Shape.** Es el número de elementos de cada dimensión.

Lo calculamos con el atributo `.shape`

In [ ]:
# Hay 3 elementos en el array 1-dimensional
d1 = np.array([-1, 0, 1])
d1.shape

(3,)

In [ ]:
# Hay 2 elementos en el array 2D y 2 elementos en los arrays 1D
d2 = np.array([[-3, -2], [-1, 0]])
d2.shape

(2, 2)

In [ ]:
# Hay 2 elementos en el array 3D, 2 elementos en cada array 2D y 4 elementos en cada array 1D
d3 = np.array([[[1, 2, 3, 4], [4, 3, 2, 1]], [[1, 0, 1, 0], [-1, 1, -1, 1]]])
d3.shape

(2, 2, 4)

La tupla resultante del atributo `.shape` se interpreta del siguiente modo:
* Cada elemento de la tupla nos indica el número de elementos que hay en cada dimensión.
* El primer índice se corresponde con la mayor dimensión, correspondiente al valor obtenido con `ndim`.
* El último índice se corresponde con la menor dimensión (dimensión 1).

Aquí es donde podemo observar la razón por la cuál todos los arrays de misma dimensión $m$ pertenecientes a un array $n$-dimensional, debe tener el mismo número de elementos.

Por ejemplo, dado un array 4D, todos los arrays 2D pertenecientes a este deben tener el mismo número de elementos, que será el que nos devuelva la tupla resultante de aplicar `.shape` en el índice correspondiente, que en este caso sería el índice 2 (tercer y penúltimo elemento de la tupla).

### Reshape de un array

**Reshape.** Cambiar la `shape` de un array

Mediante el proceso de reshape, podemos añadir o eliminar dimensiones, o bien cambiar el número de elementos de cada dimensión.

---
#### Ejemplo 1

Partiremos de un array 1D con 8 elementos y lo transformaremos en un array 2D con 2 arrays 1D, cada uno de ellos con 4 elementos.

In [ ]:
d1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("d1 =", d1)
print("Dimensión:", d1.ndim)
print("Shape:", d1.shape)

d1 = [1 2 3 4 5 6 7 8]
Dimensión: 1
Shape: (8,)


Nuestro array 1D `d1` consta de 8 elementos.

In [ ]:
d2 = d1.reshape(2, 4)
print("d2 =", d2)
print("Dimensión:", d2.ndim)
print("Shape:", d2.shape)

d2 = [[1 2 3 4]
 [5 6 7 8]]
Dimensión: 2
Shape: (2, 4)


Nuestro nuevo array 2D `d2` consta de 2 arrays de dimensión 1, con 4 elementos cada uno. De modo que en total, seguimos teniendo los 8 elementos originales, pero con diferente `shape`.

**¡Cuidado!** A la hora de llevar a cabo un reshape, el producto de los elementos de la tupla resultante de aplicar `.shape` debe coincidir con el número total de elementos que tiene el array orignial.

En este caso, partíamos de 8 elementos en 1 dimensión y hemos acabado en $2\cdot 4 = 8$ elementos distribuidos en 2 dimensiones.

---

---
#### Ejemplo 2

En este caso, partiremos de un array 1D y lo transformaremos en un array 3D

In [ ]:
d1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("d1 =", d1)
print("Dimensión:", d1.ndim)
print("Shape:", d1.shape)

d1 = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Dimensión: 1
Shape: (16,)


Nuestro array 1D consta de 16 elementos.

In [ ]:
d3 = d1.reshape(2, 4, 2)
print("d3 =", d3)
print("Dimensión:", d3.ndim)
print("Shape:", d3.shape)

d3 = [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
Dimensión: 3
Shape: (2, 4, 2)


Nuestro array 3D consta de 2 arrays bidimensionales, cada uno con 4 arrays 1D, cada cual contiene 2 elementos.

En total, hay $2\cdot 4\cdot 2 = 16$ elementos, tal y como teníamos originalmente.

---

#### Ejemplo 3

En este caso, vamos a transformar un array 2D a un array 5D.

In [ ]:
d2 = np.array([[-10, -9, -8, -7], [-6, -5, -4, -3], [-2, -1, 1, 2], [3, 4, 5, 6], [7, 8, 9, 10]])
print("d2 =", d2)
print("Dimensión:", d2.ndim)
print("Shape:", d2.shape)

d2 = [[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   1   2]
 [  3   4   5   6]
 [  7   8   9  10]]
Dimensión: 2
Shape: (5, 4)


Partimos de un array 2D, que tiene 5 arrays 1D, cada uno con 4 elementos. En total hay 20 elementos.

In [ ]:
d5 = d2.reshape(2, 1, 2, 1, 5)
print("d5 =", d5)
print("Dimensión:", d5.ndim)
print("Shape:", d5.shape)

d5 = [[[[[-10  -9  -8  -7  -6]]

   [[ -5  -4  -3  -2  -1]]]]



 [[[[  1   2   3   4   5]]

   [[  6   7   8   9  10]]]]]
Dimensión: 5
Shape: (2, 1, 2, 1, 5)


Hemos transformado nuestro array original 2D en un array 5D que consta de 2 arrays 4D, cada uno de los cuales contiene un array 3D, que tiene 2 arrays 2D con 1 array 1D en su interior que consta de 5 elementos. En total, $2\cdot 1\cdot 2\cdot 1\cdot 5 = 20$

---

**Observación.** El resultado de un `.reshape()` es una `view` del array original.

In [ ]:
print("El array transformado a partir del array d2 del Ejemplo 3 es una view,\npues al aplicar .base se nos devuelve el array 2D original:\n", d5.base)

El array transformado a partir del array d2 del Ejemplo 3 es una view,
pues al aplicar .base se nos devuelve el array 2D original:
 [[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   1   2]
 [  3   4   5   6]
 [  7   8   9  10]]


#### Dimensión desconocida

Al hacer un reshape no siempre hay que especificar el número exacto de una de las dimensiones como parámetro del método `.reshape()`.

Si desconocemos una dimensión, basta indicar -1 en el lugar adecuado y `numpy` la calculará por nosotros.

Tomando el array 2D del Ejemplo 3,

In [ ]:
d2 = np.array([[-10, -9, -8, -7], [-6, -5, -4, -3], [-2, -1, 1, 2], [3, 4, 5, 6], [7, 8, 9, 10]])

supongamos que no sabemos la última dimensión a la hora de transformarlo al array 5D. En ese caso, introducimos -1 como parámetro.

In [ ]:
d5 = d2.reshape(2, 1, 2, 1, -1)
print("d5 =", d5)
print("Dimensión:", d5.ndim)
print("Shape:", d5.shape)

d5 = [[[[[-10  -9  -8  -7  -6]]

   [[ -5  -4  -3  -2  -1]]]]



 [[[[  1   2   3   4   5]]

   [[  6   7   8   9  10]]]]]
Dimensión: 5
Shape: (2, 1, 2, 1, 5)


Observamos que `numpy` ha calculado dicha dimensión por nosotros, que coincide con el resultado indicado en el Ejemplo 3.

**¡Cuidado!** Solamente podemos pasar -1 por parámetro al método `.reshape()` para una sola dimensión.

**Observación.** El uso del -1 nos puede ser muy útil cuando queramos transformar cualquier array multidimensional a un array unidimensional.

Por ejemplo, partiendo del array 5D del Ejemplo 3, lo podemos trasformar a array undimensional del siguiente modo:

In [ ]:
d1 = d5.reshape(-1)
print("d1 =", d1)
print("Dimensión:", d1.ndim)
print("Shape:", d1.shape)

d1 = [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   1   2   3   4   5   6   7   8
   9  10]
Dimensión: 1
Shape: (20,)


### Elementos de un array


#### Caso unidimensional

Podemos acceder a los elementos de un array con la sintaxis `[]`.

**Observación.** Recordad que en `Python` los índices empezaban en 0

In [ ]:
a = np.array([2, 3, 4, 5, 6])
print(a)

print("Primer elemento = ", a[0])
print("Segundo elemento = ", a[1])
print("Último elemento = ", a[-1])

[2 3 4 5 6]
Primer elemento = 2
Segundo elemento =  3
Último elemento =  6


#### Caso multidimensional

A la hora de acceder a elementos de un array multidimensional, tendremos que empezar indicando el índice del elemento en el nivel menos profundo y acabar indicando el índice del elemento en en nivel más profundo, todos entre `[]` separados por comas.

En el caso de un array bidimiensional, como el que se muestra a continuación,

In [ ]:
a = np.array([[-10, -9], [7, 8]])
a.ndim

2

Para acceder al elemento -9, primero habrá que indicar el índice 0, pues el array unidimensional al que pertenece se encuentra en el índice 0 del nivel menos profundo. A continuación, indicaremos el índice 1, pues esa es la posición que ocupa el elemento de nuestro interés dentro del array unidimensional, que se trata del nivel más profundo en este caso:

In [ ]:
a[0, 1]

-9

En el caso de un array tridimensional, como el que se muestra a continuación,

In [ ]:
a = np.array([[[1, 2, 3], [-3, -2, -1]], [[4, 5, 6], [7, 8, 9]]])
a.ndim

3

Para acceder al elemento 7, primero habrá que indicar el índice 1, pues el array 2-dimensional al que pertenece se encuentra en la posición 1 del nivel menos profundo. Entramos en el siguiente nivel, el array 2-dimensional. Ahora, la posición que hay que indicar es la 1, pues el array 1-dimensional ocupa dicho índice dentro del array 2-dimensional. Finalmente, llegamos al nivel más profundo, el array 1-dimensional, y ahora hay que indicar el índice 0, pues esa es la posición que ocupa el elemento de nuestro interés dentro del array unidimensional.

In [ ]:
a[1, 1, 0]

7

Dado un array multidimensional, si lo que queremos es que se nos devuelva un array de dimensión menor, entonces solamnente tenemos que indicar sus índices tal cuál hacíamos para obtener un elemento.

Dado el array `a` tridimensional anterior, si queremos acceder al array unidimensional `[-3, -2, -1]`, entonces indicaremos entre `[]` los índices 0 y, a continuación, 1. Pues dicho array se encuentra en el primer array bidimensional y dentro de éste, ocupa la segunda posición, es decir, el índice 1:

In [ ]:
a[0, 1]

array([-3, -2, -1])

#### Índices negativos

Al igual que para el caso de las listas, los elementos de los `ndarrays` también pueden ser accedidos mediante índices negativos.

El índice `-1` hace referencia al último elemento; el `-2`, al penúltimo; el `-3` al antepenúltimo; y así sucesivamente.

In [ ]:
a[-1]

array([[4, 5, 6],
       [7, 8, 9]])

### Slicing

En `Python`, **slicing** hace referencia a tomar elementos desde un índice dado hasta otro proporcionado.

Ya conocemos la sintaxis:

* `[inicio:fin]` donde iremos desde el índice `inicio` hasta el índice `fin`-1, y lo haremos de 1 en 1
* `[inicio:fin:paso]` donde iremos desde el índice `inicio` hasta el índice `fin`-1, y lo haremos de `paso` en `paso`



#### Caso unidimensional

In [ ]:
# Array unidimensional
a1 = np.array([9, 8, 7, 6, 5, 4, 3])
a1

array([9, 8, 7, 6, 5, 4, 3])

In [ ]:
# Del segundo elemento al cuarto de 1 en 1
a1[1:4]

array([8, 7, 6])

In [ ]:
# Del primer elemento al sexto de 1 en 1
a1[:6]

array([9, 8, 7, 6, 5, 4])

In [ ]:
# Del tercer elemento al último de 1 en 1
a1[2:]

array([7, 6, 5, 4, 3])

In [ ]:
# Del segundo elemento al sexto de 2 en 2
a1[1:6:2]

array([8, 6, 4])

In [ ]:
# Del primer elemento al quinto de 2 en 2
a1[:5:2]

array([9, 7, 5])

In [ ]:
# Del segundo elemento al último de 3 en 3
a1[1::3]

array([8, 5])

In [ ]:
# Del primer elemento al último de 4 en 4
a1[::4]

array([9, 5])

#### Caso multidimensional


In [ ]:
# Array 4-dimensional
a4 = np.array([[[[-211, -210], [-29, -28], [-27, -26]], [[-25, -24], [-23, -22], [-21, -20]]],
               [[[-111, -110], [-19, -18], [-17, -16]], [[-15, -14], [-13, -12], [-11, -10]]],
               [[[111, 110], [19, 18], [17, 16]], [[15, 14], [13, 12], [11, 10]]],
               [[[211, 210], [29, 28], [27, 26]], [[25, 24], [23, 22], [21, 20]]]])
a4.ndim

4

In [ ]:
a4.shape

(4, 2, 3, 2)

El array 4-dimensional `a4` consta de 4 arrays tridimensionales, cada uno de ellos con 2 arrays bidimensionales que contienen cada uno 3 arrays unidimensionales.

In [ ]:
# Mostramos del segundo al tercer array 3D
a4[1:3]

array([[[[-111, -110],
         [ -19,  -18],
         [ -17,  -16]],

        [[ -15,  -14],
         [ -13,  -12],
         [ -11,  -10]]],


       [[[ 111,  110],
         [  19,   18],
         [  17,   16]],

        [[  15,   14],
         [  13,   12],
         [  11,   10]]]])

In [ ]:
# Del segundo array 2D del primer array 3D, mostramos los dos primeros arrays 1D
a4[0, 1, :2]

array([[-25, -24],
       [-23, -22]])

In [ ]:
# Del segundo al último array 3D, mostramos el segundo array 1D del primer array 2D
a4[1:, 0, 1]

array([[-19, -18],
       [ 19,  18],
       [ 29,  28]])

**Observación.** Al igual que para acceder a elementos, los índices negativos también funcionan en el slicing de arrays (Negative Slicing)

In [ ]:
# De los dos últimos arrays 3D, mostramos el último elemento de, del último array 1D de cada array 2D
a4[-2:, :, -1, -1]

array([[16, 10],
       [26, 20]])

### Filtrando arrays

Filtrar un array implica la selección de elementos de un array existente que satisfagan una condición y crear un nuevo array con dichos elementos.

La sintaxis es muy similar al slicing, pero en vez de eso, entre corchetes indicamos una condición booleana. Los elementos que satisfagan la condición serán los que permanezcan, mientras que el resto serán omitidos.

Visto de otro modo, la condición crea un array booleano. Aquellas posiciones ocupadas por un `True` serán las contenidas en el array filtrado, mientras que las que estén ocupadas por `False` (porque no satisfacen la condición), serán descartadas.

In [ ]:
a = np.array([4, 3, 2, 3, 4])
b = a[a == 4]
print(b)

[4 4]


In [ ]:
a == 4

array([ True, False, False, False,  True])

In [ ]:
c = a[a % 2 == 0]
print(c)

[4 2 4]


In [ ]:
d = a[a <= 2]
print(d)

[2]


In [ ]:
d5[d5 % 2 == 0]

array([-10,  -8,  -6,  -4,  -2,   2,   4,   6,   8,  10])

### Tipos de datos en `numpy`

Por defecto, `Python` tiene los siguientes tipos de dato:

* `int`: integer
* `float`: float
* `complex`: complex float
* `bool`: boolean
* `str`: string

En `numpy` encontramos tipos de datos adicicionales

* `i`: integer
* `u`: unsigned integer
* `f`: float
* `c`: complex float
* `b`: boolean
* `m`: timedelta
* `M`: datetime
* `O`: object
* `S`: string
* `U`: unicode string
* `V`: void

Para comprobar el tipo de dato de un array, usamos el método `.dtype`

In [ ]:
a = np.array([1, 2, 3])
print(a)
a.dtype

[1 2 3]


dtype('int64')

**Observación.** Como podéis ver, no solo se muestra el tipo de dato, sino también el tamaño

In [ ]:
a = np.array([1.5, 2.4, 3.7])
print(a)
a.dtype

[1.5 2.4 3.7]


dtype('float64')

In [ ]:
a = np.array([1j, 2 + 3j, 3 - 7j])
print(a)
a.dtype

[0.+1.j 2.+3.j 3.-7.j]


dtype('complex128')

In [ ]:
a = np.array(["araña", "barco", "colonia"])
print(a)
a.dtype

['araña' 'barco' 'colonia']


dtype('<U7')

In [ ]:
a = np.array(["a", "b", "c"])
print(a)
a.dtype

['a' 'b' 'c']


dtype('<U1')

Al usar el método `.array()`, existe un parámetro `dtype` que nos permite definir el tipo de dato que queremos que tengan los elementos de dicho ndarray

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "S")
print(a)
a.dtype

[b'1' b'2' b'3' b'4' b'5']


dtype('S1')

**Observación.** Para el caso de los tipos de dato `i`, `u`, `f`, `S` y `U`, con el parámetro `dtype` también podemos definir el tamaño

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "i1")
print(a)
a.dtype

[1 2 3 4 5]


dtype('int8')

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "i2")
print(a)
a.dtype

[1 2 3 4 5]


dtype('int16')

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "f8")
print(a)
a.dtype

[1. 2. 3. 4. 5.]


dtype('float64')

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "c16")
print(a)
a.dtype

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


dtype('complex128')

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "S2")
print(a)
a.dtype

[b'1' b'2' b'3' b'4' b'5']


dtype('S2')

Si queremos cambiar el tipo de dato de un array existente, usamos el método `.astype()`

In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "f16")
print("El array a es de tipo", a.dtype)
b = a.astype("i")
print("El array b es de tipo", b.dtype)

El array a es de tipo float128
El array b es de tipo int32


In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype = "f16")
print("El array a es de tipo", a.dtype)
b = a.astype(int)
print("El array b es de tipo", b.dtype)

El array a es de tipo float128
El array b es de tipo int64


In [ ]:
a = np.array([1, 0, 3, 0, 5, -10])
print(a)
print("El array a es de tipo", a.dtype)
b = a.astype(bool)
print(b)
print("El array b es de tipo", b.dtype)

[  1   0   3   0   5 -10]
El array a es de tipo int64
[ True False  True False  True  True]
El array b es de tipo bool


### Copias y Views de arrays

**Copia.** Una copia de un array crea un nuevo array exactamente igual al original.

La copia no es afectada pos los cambios aplicados en el array original.

In [ ]:
x = np.array(["a", "b", "c"])
print(x)
x_copy = x.copy()
print(x_copy)

['a' 'b' 'c']
['a' 'b' 'c']


**View.** Una view de un array es una referencial al array original.

Los cambios aplicados al array original afectan también a la view, y viceversa.

In [ ]:
y = np.array([1, 2, 3])
print("y =", y)
y_view = y.view()
print("y_view =", y_view)

y = [1 2 3]
y_view = [1 2 3]


Si modificamos el original, veremos los cambios también aplicados en la view

In [ ]:
y[1] = 0
print("y =", y)
print("y_view =", y_view)

y = [1 0 3]
y_view = [1 0 3]


Si modificamos la view, veremos los cambios también aplicados en el array original

In [ ]:
y_view[0] = -3
print("y =", y)
print("y_view =", y_view)

y = [-3  0  3]
y_view = [-3  0  3]


Para asegurarnos de si hemos hecho una copia o una view, podemos usar el método `.base`, que nos devolverá `None` si se trata de una copia y nos devolverá el array original si se trata de una view.

In [ ]:
z = np.array([1j, 0, -1j])
z_copy = z.copy()
z_view = z.view()

print("z_copy nos devuelve", z_copy.base, "porque es una copia")
print("z_view nos devuelve", z_view.base, "porque es una view")

z_copy nos devuelve None porque es una copia
z_view nos devuelve [ 0.+1.j  0.+0.j -0.-1.j] porque es una view


### Arrays y bucles

Podemos iterar un array tal cual lo hacíamos con listas:

#### Array 1D

In [ ]:
d1 = np.array(["a", "b", "c"])

for i in d1:
  print(i)

a
b
c


#### Array 2D

In [ ]:
d2 = np.array([["a", "b", "c"], [1, 2, 3]])

In [ ]:
# Imprimimos los elementos del array 2D
for d1 in d2:
  print(d1)

['a' 'b' 'c']
['1' '2' '3']


In [ ]:
# Imprimimos los elementos de los arrays 1D
for d1 in d2:
  for i in d1:
    print(i)

a
b
c
1
2
3


#### Array 3D

In [ ]:
d3 = np.array([[["a", "b", "c", "d"], ["e", "f", "g", "h"]], [[1, 2, 3, 4], [5, 6, 7, 8]]])
d3.dtype

dtype('<U1')

In [ ]:
# Imprimimos los elementos del array 3D
for d2 in d3:
  print(d2)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']]
[['1' '2' '3' '4']
 ['5' '6' '7' '8']]


In [ ]:
# Imprimimos los elementos de los arrays 2D
for d2 in d3:
  for d1 in d2:
    print(d1)

['a' 'b' 'c' 'd']
['e' 'f' 'g' 'h']
['1' '2' '3' '4']
['5' '6' '7' '8']


In [ ]:
# Imprimimos los elementos de los arrays 1D
for d2 in d3:
  for d1 in d2:
    for i in d1:
      print(i)

a
b
c
d
e
f
g
h
1
2
3
4
5
6
7
8


Como vemos, cada vez que aumentamos la dimensión del array, hay que anidar bucles `for` para imprimir cada uno de los elementos de los arrays 1D.

Como alternativa podríamos hacer un reshape del array multidimensional a un array unidimensional, pero dado un array con dimensión suficientemente grande, este proceso sería computacionalmente muy costoso:

In [ ]:
for i in d3.reshape(-1):
  print(i)

a
b
c
d
e
f
g
h
1
2
3
4
5
6
7
8


#### El método `.nditer()`

Para evitarnos tantas líneas de código y tanto coste computacional, tenemos el método `.nditer()`, que nos crea un iterable el cual nos permite imprimir todos los elementos de los arrays 1D, tal cuál hemos estado obteniendo hasta ahora:

In [ ]:
for i in np.nditer(d3):
  print(i)

a
b
c
d
e
f
g
h
1
2
3
4
5
6
7
8


El método `.nditer()` también nos permite cambiar el tipo de dato de los elementos de un array durante la iteración mediante el parámetro `op_dtypes`.

`numpy` no ambia el tipo de dato de los elementos de un array en el sitio, de modo qu enecesita algún otro espacio para llevar a cabo esta acción. Este espacio extra es llamado **buffer** y se lo proporcionamos al método `.nditer()` con el argumento `flags = ["buffered"]`

In [ ]:
d2 = np.array([[1, 2], [3, 4], [5, 6]])
for i in np.nditer(d2, flags = ["buffered"], op_dtypes = ["S"]):
  print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


El método `.nditer()` también nos permite iterar con distinto paso (de 1 en 1, de 2 en 2, ...)

In [ ]:
d2 = np.array([[1, 2], [3, 4], [5, 6]])
for i in np.nditer(d2[:, ::2]):
  print(i)

1
3
5


#### El método `.ndenumerate()`

A veces necesitamos el índice correspondiente al elemento durante la iteración. El método `.ndenumerate()` nos proporciona dicha información.



In [ ]:
d1 = np.array(["a", "b", "c"])

for idx, i in np.ndenumerate(d1):
  print("Índice:", idx,"Elemento:", i)

Índice: (0,) Elemento: a
Índice: (1,) Elemento: b
Índice: (2,) Elemento: c


In [ ]:
d2 = np.array([[1, 2], [3, 4], [5, 6]])

for idx, i in np.ndenumerate(d2):
  print("Índice:", idx,"Elemento:", i)

Índice: (0, 0) Elemento: 1
Índice: (0, 1) Elemento: 2
Índice: (1, 0) Elemento: 3
Índice: (1, 1) Elemento: 4
Índice: (2, 0) Elemento: 5
Índice: (2, 1) Elemento: 6


In [ ]:
d3 = np.array([[["a", "b", "c", "d"], ["e", "f", "g", "h"]], [[1, 2, 3, 4], [5, 6, 7, 8]]])

for idx, i in np.ndenumerate(d3):
  print("Índice:", idx,"Elemento:", i)

Índice: (0, 0, 0) Elemento: a
Índice: (0, 0, 1) Elemento: b
Índice: (0, 0, 2) Elemento: c
Índice: (0, 0, 3) Elemento: d
Índice: (0, 1, 0) Elemento: e
Índice: (0, 1, 1) Elemento: f
Índice: (0, 1, 2) Elemento: g
Índice: (0, 1, 3) Elemento: h
Índice: (1, 0, 0) Elemento: 1
Índice: (1, 0, 1) Elemento: 2
Índice: (1, 0, 2) Elemento: 3
Índice: (1, 0, 3) Elemento: 4
Índice: (1, 1, 0) Elemento: 5
Índice: (1, 1, 1) Elemento: 6
Índice: (1, 1, 2) Elemento: 7
Índice: (1, 1, 3) Elemento: 8


### Concatenación de arrays

Para concatenar arrays, es decir, juntar dos o más arrays en un único array, usamos el método `.concatenate()`

In [ ]:
# Conatenamos arrays 1D
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])
a = np.concatenate((a1, a2))
print(a)

[-3 -2 -1  1  2  3]


In [ ]:
# Concatenamos arrays 2D
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])

# Con axis = 0
b = np.concatenate((b1, b2), axis = 0)
print("axis = 0 nos devuelve\n", b)

# Con axis = 1
b = np.concatenate((b1, b2), axis = 1)
print("\naxis = 1 nos devuelve\n", b)

axis = 0 nos devuelve
 [[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 1  2]
 [ 3  4]
 [ 5  6]]

axis = 1 nos devuelve
 [[-6 -5  1  2]
 [-4 -3  3  4]
 [-2 -1  5  6]]


**Observación.** En este caso, nos funcionan ambas configuraciones del valor `axis` pues los dos arrays 2D, `b1` y `b2` tienen tanto el mismo número de arrays 1D como el mismo número de elementos dentro de cada array 1D.

Si indicamos `axis = 0`, se nos combinan ambos arrays 2D en un solo array 2D. En este caso es necesario que todos los arrays 1D tengan el mismo número de elementos.

Sin embargo, si seleccionamos `axis = 1`, entonces obtenemos como resultado un array 2D con cada uno de los arrays 1D concatenados. En este caso necesitamos que en ambos arrays 2D haya el mismo número de arrays 1D.

In [ ]:
# Concatenamos arrays 3D
c1 = np.array([[[-10, -9], [-8, -7], [-6, -5]], [[-4, -3], [-2, -1], [0, 0]]])
c2 = np.array([[[0, 0], [1, 2], [3, 4]], [[5, 6], [7, 8], [9, 10]]])

# Con axis = 0
c = np.concatenate((c1, c2), axis = 0)
print("axis = 0 nos devuelve\n", c)

# Con axis = 1
c = np.concatenate((c1, c2), axis = 1)
print("\naxis = 1 nos devuelve\n", c)

# Con axis = 2
c = np.concatenate((c1, c2), axis = 2)
print("\naxis = 2 nos devuelve\n", c)

axis = 0 nos devuelve
 [[[-10  -9]
  [ -8  -7]
  [ -6  -5]]

 [[ -4  -3]
  [ -2  -1]
  [  0   0]]

 [[  0   0]
  [  1   2]
  [  3   4]]

 [[  5   6]
  [  7   8]
  [  9  10]]]

axis = 1 nos devuelve
 [[[-10  -9]
  [ -8  -7]
  [ -6  -5]
  [  0   0]
  [  1   2]
  [  3   4]]

 [[ -4  -3]
  [ -2  -1]
  [  0   0]
  [  5   6]
  [  7   8]
  [  9  10]]]

axis = 2 nos devuelve
 [[[-10  -9   0   0]
  [ -8  -7   1   2]
  [ -6  -5   3   4]]

 [[ -4  -3   5   6]
  [ -2  -1   7   8]
  [  0   0   9  10]]]


**Observación.** En este caso, nos vuelven a funcionar todas las configuraciones del valor `axis` pues los dos arrays 3D, `c1` y `c2` tienen tanto el mismo número de arrays 2D, como el mismo número de arrays 1D en cada array 2D, como el mismo número de elementos dentro de cada array 1D.

Si indicamos `axis = 0`, se nos combinan ambos arrays 3D en un solo array 3D. Por su parte, si seleccionamos `axis = 1`, entonces obtenemos como resultado un array 3D con cada uno de los arrays 2D concatenados. Por último, si indicamos `axis = 2`, obtendremos un array 3D donde los arrays 1D han sido concatenados.

**Observación.** Si queremos concatenar arrays $n$-dimensionales, tendremos $n-1$ opciones para el parámetro `axis`.

#### Concatenación de arrays usando `.stack()`

Llevar a cabo un stack es lo mismo que concatenar, solo que el stack se hace sobre un eje nuevo.

Por ejemplo, podemos concatenar dos arrays unidimensionales sobre un segundo eje, lo que resultaría en poner un array sobre el otro: realizar un stack.

In [ ]:
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])

In [ ]:
# Hacemos stack de arrays 1D con axis = 0
a = np.stack((a1, a2), axis = 0)
print(a)

[[-3 -2 -1]
 [ 1  2  3]]


In [ ]:
# Hacemos stack de arrays 1D con axis = 1
a = np.stack((a1, a2), axis = 1)
print(a)

[[-3  1]
 [-2  2]
 [-1  3]]


**Observación.** Al hacer stack de los arrays 1D, habiendo seleccionado `axis = 0`, obtenemos como resultado un array 2D con los dos arrays 1D originales. Sin embargo, si elegimos `axis = 1`, obtenemos nuevamente un array 2D, pero éste consta de 3 elementos 1D (en este ejemplo en concreto), cada cual con 2 elementos (el primero se corresponde con un elemento del array original `a1`, mientras que el segundo, con un elemento del array `a2`)

In [ ]:
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
# Hacemos stack de arrays 2D con axis = 0
b = np.stack((b1, b2), axis = 0)
print(b)

[[[-6 -5]
  [-4 -3]
  [-2 -1]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]]]


In [ ]:
# Hacemos stack de arrays 2D con axis = 1
b = np.stack((b1, b2), axis = 1)
print(b)

[[[-6 -5]
  [ 1  2]]

 [[-4 -3]
  [ 3  4]]

 [[-2 -1]
  [ 5  6]]]


In [ ]:
# Hacemos stack de arrays 2D con axis = 2
b = np.stack((b1, b2), axis = 2)
print(b)

[[[-6  1]
  [-5  2]]

 [[-4  3]
  [-3  4]]

 [[-2  5]
  [-1  6]]]


**Observación.** Al hacer stack de los arrays 2D, habiendo seleccionado `axis = 0`, obtenemos como resultado un array 3D con los dos arrays 2D originales. Por su parte, si elegimos `axis = 1`, obtenemos nuevamente un array 3D, pero éste consta de 3 elementos 2D (en este ejemplo en concreto), cada cual con 2 elementos 1D (el primero se corresponde con un elemento del array original `b1`, mientras que el segundo, con un elemento del array `b2`). Por último, si consideramos `axis = 2`, obtenemos también un array 3D, que consta de 3 elementos 2D (en este ejemplo en concreto), cada uno con 2 elementos 1D que han sido concatenados del siguiente modo: el primer elemento del array 1D se corresponde con un elemento original del array `b1`, mientras que el segundo y último elemento del array 1D procede del array `b2`.

**Observación.** Si queremos hacer stack de arrays $n$-dimensionales, tendremos $n$ opciones para el parámetro `axis` y siempre obtendremos como resultado un array de dimensión $n+1$ que ha sido combinado según el `axis` seleccionado.

#### Concatenando por filas

`numpy` proporciona la función helper `hstack()` que lleva a cabo una concatenación por filas:

In [ ]:
# Caso 1D (se corresponde con el resultado de .concatenate())
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])
a = np.hstack((a1, a2))
print(a)

[-3 -2 -1  1  2  3]


In [ ]:
# Caso 2D (se corresponde con el resultado de .concatenate() con axis = 1)
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])
b = np.hstack((b1, b2))
print(b)

[[-6 -5  1  2]
 [-4 -3  3  4]
 [-2 -1  5  6]]


In [ ]:
# Caso 3D (se corresponde con el resultado de .concatenate() con axis = 1)
c1 = np.array([[[-10, -9], [-8, -7], [-6, -5]], [[-4, -3], [-2, -1], [0, 0]]])
c2 = np.array([[[0, 0], [1, 2], [3, 4]], [[5, 6], [7, 8], [9, 10]]])
c = np.hstack((c1, c2))
print(c)

[[[-10  -9]
  [ -8  -7]
  [ -6  -5]
  [  0   0]
  [  1   2]
  [  3   4]]

 [[ -4  -3]
  [ -2  -1]
  [  0   0]
  [  5   6]
  [  7   8]
  [  9  10]]]


#### Concatenando por columnas

`numpy` proporciona la función helper `vstack()` que lleva a cabo una concatenación por columnas:

In [ ]:
# Caso 1D (se corresponde con el resultado de .stack() con axis = 0)
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])
a = np.vstack((a1, a2))
print(a)

[[-3 -2 -1]
 [ 1  2  3]]


In [ ]:
# Caso 2D (se corresponde con el resultado de .concatenate() con axis = 0)
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])
b = np.vstack((b1, b2))
print(b)

[[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 1  2]
 [ 3  4]
 [ 5  6]]


In [ ]:
# Caso 3D (se corresponde con el resultado de .concatenate() con axis = 0)
c1 = np.array([[[-10, -9], [-8, -7], [-6, -5]], [[-4, -3], [-2, -1], [0, 0]]])
c2 = np.array([[[0, 0], [1, 2], [3, 4]], [[5, 6], [7, 8], [9, 10]]])
c = np.vstack((c1, c2))
print(c)

[[[-10  -9]
  [ -8  -7]
  [ -6  -5]]

 [[ -4  -3]
  [ -2  -1]
  [  0   0]]

 [[  0   0]
  [  1   2]
  [  3   4]]

 [[  5   6]
  [  7   8]
  [  9  10]]]


#### Concatenando por profundidad

`numpy` proporciona la función helper `dstack()` que lleva a cabo una concatenación por profundidad:

In [ ]:
# Caso 1D (se corresponde con el resultado de .stack() con axis = 1)
a1 = np.array([-3, -2, -1])
a2 = np.array([1, 2, 3])
a = np.dstack((a1, a2))
print(a)

[[[-3  1]
  [-2  2]
  [-1  3]]]


In [ ]:
# Caso 2D (se corresponde con el resultado de .stack() con axis = 2)
b1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
b2 = np.array([[1, 2], [3, 4], [5, 6]])
b = np.dstack((b1, b2))
print(b)

[[[-6  1]
  [-5  2]]

 [[-4  3]
  [-3  4]]

 [[-2  5]
  [-1  6]]]


In [ ]:
# Caso 3D (se corresponde con el resultado de .concatenate() con axis = 2)
c1 = np.array([[[-10, -9], [-8, -7], [-6, -5]], [[-4, -3], [-2, -1], [0, 0]]])
c2 = np.array([[[0, 0], [1, 2], [3, 4]], [[5, 6], [7, 8], [9, 10]]])
c = np.dstack((c1, c2))
print(c)

[[[-10  -9   0   0]
  [ -8  -7   1   2]
  [ -6  -5   3   4]]

 [[ -4  -3   5   6]
  [ -2  -1   7   8]
  [  0   0   9  10]]]


### División de arrays

El proceso inverso a la concatenación es la división de arrays. La división de arrays consiste en romper un array en múltiples arrays.

Para dividir arrays usamos el método `.array_split()`

#### Dividiendo arrays 1D

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.array_split(x, 4)
print("Del array original x =", x)
print("Dividiéndolo en 4 obtenemos:", y)

Del array original x = [1 2 3 4 5 6 7 8]
Dividiéndolo en 4 obtenemos: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


Como resultado, obtenemos una lista con el número de arrays 1D que hemos indicado por parámetro.

**Observación.** El array original lo podemos dividir en 2, 3,... hasta en tantos arrays como elementos contenga. Es decir, dado por ejemplo un array 1D con 8 elementos, podemos dividirlo en 2, 3, 4, ..., 8 arrays:

In [ ]:
for i in range(2, x.shape[0] + 1):
  print("Dividimos en {} arrays: {}".format(i, np.array_split(x, i)))

Dividimos en 2 arrays: [array([1, 2, 3, 4]), array([5, 6, 7, 8])]
Dividimos en 3 arrays: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
Dividimos en 4 arrays: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
Dividimos en 5 arrays: [array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]
Dividimos en 6 arrays: [array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8])]
Dividimos en 7 arrays: [array([1, 2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8])]
Dividimos en 8 arrays: [array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8])]


**Observación.** Si el número de arrays en que queremos dividir el array original, $m$, es divisor del número de elementos que tiene el array original, $n$, entonces todos los arrays resultantes tendrán el mismo número de elementos, $q$, donde $q$ es el cociente de la división entera de $n$ entre $m$.

En cambio, si el número introducido por parámetro, $m$, no es divisor del número total de elementos del array original, $n$, entonces los $r$ primeros arrays resultantes, siendo $r$ el resto de la división entera de $n$ entre $m$, tendrán cada uno de ellos $q + 1$ elementos, mientras que el resto de arrays, los $m-r$ restantes, tendrán $q$ elementos. De modo que

$$n = r\cdot (q + 1) + (m - r)\cdot q = qr + r + mq - qr = mq + r $$


---
#### Ejemplo 4

Consideremos un array 1D con 20 elementos. Entonces,

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

n = a.shape[0]
for m in range(2, n + 1):
  print("\nDividimos el array original en {} arrays".format(m))
  q = n//m
  r = n % m
  print("n = {}, m = {}, q = {}, r = {}".format(n, m, q, r))

  if r == 0:
    print("Los {} arrays resultantes tienen el mismo número de elementos: {}".format(m, q))

  else:
    print("Los primeros {} arrays tienen {} elementos. El resto de los arrays tienen {} elementos".format(r, q + 1, q))

  for i in np.array_split(a, m):
    print(i)


Dividimos el array original en 2 arrays
n = 20, m = 2, q = 10, r = 0
Los 2 arrays resultantes tienen el mismo número de elementos: 10
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]

Dividimos el array original en 3 arrays
n = 20, m = 3, q = 6, r = 2
Los primeros 2 arrays tienen 7 elementos. El resto de los arrays tienen 6 elementos
[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]
[15 16 17 18 19 20]

Dividimos el array original en 4 arrays
n = 20, m = 4, q = 5, r = 0
Los 4 arrays resultantes tienen el mismo número de elementos: 5
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]

Dividimos el array original en 5 arrays
n = 20, m = 5, q = 4, r = 0
Los 5 arrays resultantes tienen el mismo número de elementos: 4
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]

Dividimos el array original en 6 arrays
n = 20, m = 6, q = 3, r = 2
Los primeros 2 arrays tienen 4 elementos. El resto de los arrays tienen 3 elementos
[1 2 3 4]
[5 6 7 8]
[ 9 10 11]
[12 13 14]
[15

---



#### El método `.split()`

A la hora de dividir arrays tenemos también el método `.split()`, pero falla en caso de que el número de arrays en que queramos dividir el array original no sea divisor del número de elementos del array.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.split(x, 4)
print("Del array original x =", x)
print("Dividiéndolo en 4 obtenemos:", y)

Del array original x = [1 2 3 4 5 6 7 8]
Dividiéndolo en 4 obtenemos: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


Al cumplirse que el número de arrays en que queremos dividir el array original es divisor del número de elementos del array, obtenemos el mismo resultado que al usar el método `.array_split()`.

El siguiente caso, donde queremos dividir los 8 elementos en 3 arrays, nos dará error pues la división no es exacta:

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.split(x, 3)

#### Dividiendo arrays 2D

Podemos también dividir arrays 2D en múltiples arrays 2D:

In [ ]:
x = np.array([[-1, 0, 1], [-2, 0, 2], [-3, 0, 3],
              [-4, 0, 4], [-5, 0, 5], [-6, 0, 6]])
y = np.array_split(x, 3)
print("Del array original x =\n", x)
print("Dividiéndolo en 3 obtenemos:")
for i in y:
  print(i)

Del array original x =
 [[-1  0  1]
 [-2  0  2]
 [-3  0  3]
 [-4  0  4]
 [-5  0  5]
 [-6  0  6]]
Dividiéndolo en 3 obtenemos:
[[-1  0  1]
 [-2  0  2]]
[[-3  0  3]
 [-4  0  4]]
[[-5  0  5]
 [-6  0  6]]


Como resultado, obtenemos una lista con el número de arrays 2D que hemos indicado por parámetro.

De nuevo, el array 2D original lo podemos dividir en 2, 3,... hasta en tantos arrays como elementos 1D contenga. Es decir, dado por ejemplo un array 2D con 6 arrays 1D, podemos dividirlo en 2, 3, 4, ..., 6 arrays 2D:

In [ ]:
for i in range(2, x.shape[0] + 1):
  print("\nDividimos el array original en {} arrays:".format(i))
  for j in np.array_split(x, i):
    print(j)


Dividimos el array original en 2 arrays:
[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]
[[-4  0  4]
 [-5  0  5]
 [-6  0  6]]

Dividimos el array original en 3 arrays:
[[-1  0  1]
 [-2  0  2]]
[[-3  0  3]
 [-4  0  4]]
[[-5  0  5]
 [-6  0  6]]

Dividimos el array original en 4 arrays:
[[-1  0  1]
 [-2  0  2]]
[[-3  0  3]
 [-4  0  4]]
[[-5  0  5]]
[[-6  0  6]]

Dividimos el array original en 5 arrays:
[[-1  0  1]
 [-2  0  2]]
[[-3  0  3]]
[[-4  0  4]]
[[-5  0  5]]
[[-6  0  6]]

Dividimos el array original en 6 arrays:
[[-1  0  1]]
[[-2  0  2]]
[[-3  0  3]]
[[-4  0  4]]
[[-5  0  5]]
[[-6  0  6]]


**Observación.** En el caso 2D, vuelve a satisfacerse que si el número de arrays en que queremos dividir el array 2D original, $m$, es divisor del número de elementos 1D que tiene el array original 2D, $n$, entonces todos los arrays 2D resultantes tendrán el mismo número de arrays 1D, $q$, donde $q$ es el cociente de la división entera de $n$ entre $m$.

En cambio, si el número introducido por parámetro, $m$, no es divisor del número total de arrays 1D que contiene el array original, $n$, entonces los $r$ primeros arrays 2D resultantes, siendo $r$ el resto de la división entera de $n$ entre $m$, tendrán cada uno de ellos $q + 1$ elementos, mientras que el resto de arrays 2D, los $m-r$ restantes, tendrán $q$ elementos. De modo que

$$n = r\cdot (q + 1) + (m - r)\cdot q = qr + r + mq - qr = mq + r $$

En el caso de dividir arrays multidimensionales, volvemos a tener la opción de configurar el parámetro `axis`.

In [ ]:
x = np.array([[-1, 0, 1], [-2, 0, 2], [-3, 0, 3],
              [-4, 0, 4], [-5, 0, 5], [-6, 0, 6]])
print("Del array original x =\n", x)
print("Dividiéndolo en 3 con axis = 0 obtenemos:")
y = np.array_split(x, 3, axis = 0)
for i in y:
  print(i)

print("\nDividiéndolo en 3 con axis = 1 obtenemos:")
y = np.array_split(x, 3, axis = 1)
for i in y:
  print(i)

Del array original x =
 [[-1  0  1]
 [-2  0  2]
 [-3  0  3]
 [-4  0  4]
 [-5  0  5]
 [-6  0  6]]
Dividiéndolo en 3 con axis = 0 obtenemos:
[[-1  0  1]
 [-2  0  2]]
[[-3  0  3]
 [-4  0  4]]
[[-5  0  5]
 [-6  0  6]]

Dividiéndolo en 3 con axis = 1 obtenemos:
[[-1]
 [-2]
 [-3]
 [-4]
 [-5]
 [-6]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


En el caso de `axis = 0`, obtenemos como resultado una lista de arrays 2D donde se han repartido los arrays 1D en el número de arrays 2D indicado por parámetro a la función y del modo que hemos explicado anteriormente.

En el caso de `axis = 1`, obtenemos como resultado una lista de arrays 2D, tantos como se ha indicado por parámetro, donde se han repartido los elementos de cada array 1D.

**Observación.** En el caso 2D, si configuramos `axis = 1`, si el número de arrays en que queremos dividir el array 2D original, $m$, es divisor del número de elementos contenidos en cada array 1D del array original 2D, $n$, entonces todos los arrays 2D resultantes tendrán tantos arrays 1D como tenían originalmente, los cuales tendrán todos el mismo número de elementos, $q$, donde $q$ es el cociente de la división entera de $n$ entre $m$.

En cambio, si el número introducido por parámetro, $m$, no es divisor del número total de elementos contenidos en cada array 1D del array original 2D, $n$, entonces todos los arrays 2D resultantes tendrán el mismo número de arrays 1D que el original, pero los arrays 1D de los $r$ primeros arrays 2D resultantes, siendo $r$ el resto de la división entera de $n$ entre $m$, tendrán cada uno de ellos $q + 1$ elementos, mientras que los arrays 1D para el resto de arrays 2D, los $m-r$ restantes, tendrán $q$ elementos cada uno de ellos. De modo que

$$n = r\cdot (q + 1) + (m - r)\cdot q = qr + r + mq - qr = mq + r $$

**Observación.** Para el caso de `axis = 1`, podremos dividir el array original en 2, 3, ..., hasta el número de elementos que contengan cada uno de los arrays 1D del array 2D original.

---
#### Ejemplo 5

Consideremos un array 2D con 4 arrays 1D, cada uno de los cuales contiene 5 elementos.

In [ ]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print("La shape del array 2D original es:", a.shape)

n = a.shape[-1] # Tomamos el número de elementos que contiene cada array 1D
for m in range(2, n + 1):
  print("\nDividimos el array original 2D en {} arrays con axis = 1".format(m))
  q = n//m
  r = n % m
  print("n = {}, m = {}, q = {}, r = {}".format(n, m, q, r))

  print("Los {} arrays resultantes contienen el mismo número de arrays 1D que el original".format(m), sep = " ")
  if r == 0:
    print("cada uno de ellos con el mismo número de elementos: {}".format(q))

  else:
    print("\nEn este caso, para los primeros {} arrays 2D, cada array 1D tiene {} elementos.".format(r, q + 1))
    print("para los arrays 2D restantes, cada array 1D tiene {} elementos".format(q))

  for i in np.array_split(a, m, axis = 1):
    print(i)

La shape del array 2D original es: (4, 5)

Dividimos el array original 2D en 2 arrays con axis = 1
n = 5, m = 2, q = 2, r = 1
Los 2 arrays resultantes contienen el mismo número de arrays 1D que el original

En este caso, para los primeros 1 arrays 2D, cada array 1D tiene 3 elementos.
para los arrays 2D restantes, cada array 1D tiene 2 elementos
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]

Dividimos el array original 2D en 3 arrays con axis = 1
n = 5, m = 3, q = 1, r = 2
Los 3 arrays resultantes contienen el mismo número de arrays 1D que el original

En este caso, para los primeros 2 arrays 2D, cada array 1D tiene 2 elementos.
para los arrays 2D restantes, cada array 1D tiene 1 elementos
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]
[[ 5]
 [10]
 [15]
 [20]]

Dividimos el array original 2D en 4 arrays con axis = 1
n = 5, m = 4, q = 1, r = 1
Los 4 arrays resultantes contienen el mismo número de arrays 1D que el original

---



#### El método `.hsplit()`

`numpy` nos proporciona una función helper, el método `.hsplit()` que lleva a cabo el proceso inverso a `.hstack()`

In [ ]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

for i in np.hsplit(a, 5):
  print(i)

[[ 1]
 [ 6]
 [11]
 [16]]
[[ 2]
 [ 7]
 [12]
 [17]]
[[ 3]
 [ 8]
 [13]
 [18]]
[[ 4]
 [ 9]
 [14]
 [19]]
[[ 5]
 [10]
 [15]
 [20]]


El resultado de este método es equivalente al que obtendríamos si usáramos el método `.array_split()` con `axis = 1`. No obstante, este método dará error si el número de arrays en que queremos dividir el array original, $m$, no coincide con el número de elementos que contiene cada array 1D del array original 2D, $n$.

#### El método `.vsplit()`



`numpy` nos proporciona una función helper, el método `.vsplit()` que lleva a cabo el proceso inverso a `.vstack()`

In [ ]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

for i in np.vsplit(a, 2):
  print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


El resultado de este método es equivalente al que obtendríamos si usáramos el método `.array_split()` con `axis = 0`. No obstante, este método dará error si el número de arrays en que queremos dividir el array original, $m$, no coincide con el número de arrays 1D del array original 2D, $n$.

#### Dividiendo arrays multidimensionales

Para dividir arrays $d$-dimensionales, siendo $d > 2$, podemos usar el método `.array_split()` como hasta ahora.

A medida que $d$ sea mayor, tendremos más posibilidades para el parámetro `axis`. En concreto, tendremos $d$ posibles elecciones: `axis = 0`, `axis = 1`, ..., hasta `axis = d - 1`.

#### El método `.dsplit()`

Si tenemos arrays multidimensionales, cuya dimensión es mayor o igual a 3, entonces podremos usar el método `.dsplit()`, que se trata de una función helper, la inversa a `.dstack()` y se corresponde con el resultado de `.array_split()` con `axis = 2`.

Lo que hay que tener en cuenta que `.dsplit()` funcionará únicamente si el número de arrays $d$-dimensionales en que queremos dividir el array $d$-dimensional original, $m$, es divisor del número de elementos que contiene cada array $(d-2)$-dimensional del array original.

Si d = 3, entonces el número de arrays tridimensionales $m$ que indiquemos por parámetro deberá ser divisor del número de elementos que contiene cada array unidimensional ($d - 2 = 1$) del array tridimensional original.

In [ ]:
a = np.array([[[1, 2, 3, 4],
              [6, 7, 8, 9],
              [11, 12, 13, 14],
              [16, 17, 18, 19]],

              [[1, 2, 3, 4],
              [6, 7, 8, 9],
              [11, 12, 13, 14],
              [16, 17, 18, 19]]])

for i in np.dsplit(a, 2):
  print(i)

[[[ 1  2]
  [ 6  7]
  [11 12]
  [16 17]]

 [[ 1  2]
  [ 6  7]
  [11 12]
  [16 17]]]
[[[ 3  4]
  [ 8  9]
  [13 14]
  [18 19]]

 [[ 3  4]
  [ 8  9]
  [13 14]
  [18 19]]]


### Buscando elementos en un array

Podemos buscar elementos en concreto de un array con el método `.where()` que nos devolverá un array de índices en los cuales se encuentra el elemento que estamos buscando.

Por ejemplo, dado el siguiente array 1D `x`, busquemos en qué posiciones éste toma el valor 0.

In [ ]:
x = np.array([1, 0, -1, 0, 2, 0, -2, 0])
idx0 = np.where(x == 0)

print(idx0)

(array([1, 3, 5, 7]),)


Como resultado hemos obtenido que en los índices 1, 3, 5 y 7 del array `x` se toma el valor 0.

**Observación.** Podemos poner cualquier tipo de condición a modo de argumento del método `.where()`.

Dado el siguiente array 1D `y`, busquemos en qué índices se toman valores pares.

In [ ]:
y = np.array([2, 3, 6, 7, 14, 15, 30, 31])
z = np.where(y % 2 == 0)

print(z)

(array([0, 2, 4, 6]),)


In [ ]:
y = np.array([[2, 3, 6, 7],
              [14, 15, 30, 31]])
z = np.where(y % 2 == 0)

print(z)

(array([0, 0, 1, 1]), array([0, 2, 0, 2]))


#### El método `.searchsorted()`

El método `.searchsorted()` lleva a cabo una búsqueda binaria en el array y devuelve los índices donde el valor indicado por parámetro sería colocado de modo que se mantuviese el orden de búsqueda:

In [ ]:
a = np.array([-10, -9, -8, -7])
b = np.searchsorted(a, -9.5)
c = np.searchsorted(a, -6.5)
print("El elemento -9.5 deberá ocupar el índice", b)
print("El elemento -6.5 deberá ocupar el índice", c)

El elemento -9.5 deberá ocupar el índice 1
El elemento -6.5 deberá ocupar el índice 4


**Observación.** En caso de no proporcionar un array ya ordenado, `numpy` lo ordena por defecto:

* Los números van en orden ascendente
* Las letras y strings en orden alfabético

In [ ]:
a = np.array([-10, -8, -9, -7])
b = np.searchsorted(a, -9.5)
c = np.searchsorted(a, -6.5)
print("El elemento -9.5 deberá ocupar el índice", b)
print("El elemento -6.5 deberá ocupar el índice", c)

El elemento -9.5 deberá ocupar el índice 1
El elemento -6.5 deberá ocupar el índice 4


Por defecto, se nos devuelve el primer índice (empezando por la izquierda) que podría ocupar el elemento que queremos introducir dentro del array. Para mostrar el último índice que podría ocupar dicho elemento, existe un parámetro llamado `side` y habrá que igualarlo a `"right"` para obtener dicho índice:

In [ ]:
a = np.array([-10, -9, -8, -7])
b_left = np.searchsorted(a, -9, side = "left")
b_right = np.searchsorted(a, -9, side = "right")
c_left = np.searchsorted(a, -7, side = "left")
c_right = np.searchsorted(a, -7, side = "right")
print("El elemento -9 puede ocupar como pronto el índice", b_left)
print("El elemento -9  puede ocupar como tarde el índice", b_right)
print("El elemento -7 puede ocupar como pronto el índice", c_left)
print("El elemento -7 puede ocupar como tarde  el índice", c_right)

El elemento -9 puede ocupar como pronto el índice 1
El elemento -9  puede ocupar como tarde el índice 2
El elemento -7 puede ocupar como pronto el índice 3
El elemento -7 puede ocupar como tarde  el índice 4


En vez de ir de elemento en elemento, podemos introducir por parámetro una lista de elementos a introducir en el array:

In [ ]:
x = np.array([4, 8, 12, 16])
y = np.searchsorted(x, [3, 6, 9])
print(y)

[0 1 2]


Como resultado obtendremos un array con los índices en que se introducirían cada uno de los elementos de la lista dentro del array:

* El elemento 3 ocuparía el índice 0 dentro del array original `x`, quedando como resultado `[3, 4, 8, 12, 16]`
* El elemento 6 ocuparía el índice 1 dentro del array original `x` quedando como resultado `[4, 6, 8, 12, 16]`
* El elemento 9 ocuparía el índice 2 dentro del array original `x` quedando como resultado `[4, 8, 9, 12, 16]`

### Ordenando arrays

Ordenar arrays implica reordenar los elementos siguiendo una secuencia ordenada.

A su vez, una secuencia ordenada es cualquier sucesión que tiene un orden ciuos elementos siguen, como por ejemplo el orden alfabético o numérico, tanto ascendente como descendente.

Para ordenar los elementos de un array, disponemos del método `.sort()`

In [ ]:
x = np.array(["c", "m", "k", "z", "a"])
print(np.sort(x))

['a' 'c' 'k' 'm' 'z']


In [ ]:
x = np.array(["caracol", "mariposa", "escarabajo", "perezoso", "armadillo"])
print(np.sort(x))

['armadillo' 'caracol' 'escarabajo' 'mariposa' 'perezoso']


In [ ]:
x = np.array([2, -2, 5, -5, 10, -10, 0])
print(np.sort(x))

[-10  -5  -2   0   2   5  10]


In [ ]:
x = np.array([2.5, -2.3, 5.1, -5.7, 10.9, -10.6, 0.4])
print(np.sort(x))

[-10.6  -5.7  -2.3   0.4   2.5   5.1  10.9]


In [ ]:
x = np.array([True, False, True, False])
print(np.sort(x))

[False False  True  True]


A modo de resultado obtenemos una copia del array original, con los elementos ordenados por defecto de forma ascendente.

También podemos ordenar arrays multidimensionales:

In [ ]:
y = np.array([[2, 4, 3], [-4, -2, -3]])
print(np.sort(y))

[[ 2  3  4]
 [-4 -3 -2]]


Y podemos elegir sobre qué eje ordenarlos con el parámetro `axis`

In [ ]:
y = np.array([[2, 4, 3], [-4, -2, -3]])
print(np.sort(y, axis = 0))
print(np.sort(y, axis = 1))

[[-4 -2 -3]
 [ 2  4  3]]
[[ 2  3  4]
 [-4 -3 -2]]


Por defecto, si no indicamos el parámetro `axis` se ordena siempre con respecto al último eje.

`axis = 0` ordena los elementos dentro de la mayor dimensión. En este caso, ordena los arrays 1D dentro del array 2D.

`axis = 1` ordena los elementos dentro de la segunda mayor dimensión. En este caso, ordena los elementos de los arrays 1D.

**Observación.** Dado un array $n$-dimensional, tendremos $n$ opciones para `axis`: 0 (dimensión mayor), 1 (segunda mayor dimensión), ..., $n-1$ (dimensión menor, equivalente a no indicar parámetro `axis` o igualar `axis = -1`).

### Elementos aleatorios en `numpy`

**Número aleatorio.** Un número aleatorio singifica que se trata de un número que no puede ser predicho lógicamente.

**¡Cuidado!** No hay que confundir número aleatorio con que se genere un número diferente cada vez que ejecutemos.

Como los ordenadores trabajan mediante algoritmos, un programa destinado a generar números aleatorios implica que los números no serán realmente aleatorios. Los números aleatorios generados mediante un algoritmo son conocidos como **números pseudoaleatorios**.

En este apartado trabajaremos con números pseudoaleatorios y veremos como generarlos.



#### El módulo `random`

`numpy` tiene el módulo `random` dedicado a trabajar con números aleatorios

Para generar números enteros aleatorios, usamos el método `.randint()`


In [ ]:
from numpy import random

In [ ]:
# Generamos un número entero aleatorio del 1 al 20
n = random.randint(1, 20)
print(n)

4


In [ ]:
# Generamos un número entero aleatorio del 0 al 10
m = random.randint(10)
print(m)

7


Para generar números reales aleatorios dentro del intervalo $[0, 1]$, usamos el método `.rand()`

In [ ]:
# Generamos un número real aleatorio entre el 0 y el 1
x = random.rand()
print(x)

0.9872404246913139


#### Arrays aleatorios

Podemos generar arrays aleatorios tanto con el método `.randint()` como con el método `.rand()`

In [ ]:
# Generamos un array 1D de 5 elementos enteros aleatorios
a = random.randint(100, size = 5)
print(a)

[ 0 18 73 87 82]


In [ ]:
# Generamos un array 1D de 3 elementos reales aleatorios
b = random.rand(3)
print(b)

[0.28538885 0.24082085 0.72590504]


In [ ]:
# Generamos un array 2D de 5 arrays 1D cada uno con 4 enteros aleatorios
c = random.randint(50, size = (5, 4))
print(c)

[[12 42 26 22]
 [35 26 34 27]
 [33 40 37 23]
 [41 18 42  7]
 [23 16 20 42]]


In [ ]:
# Generamos un array 3D de 2 arrays 2D cada uno con 4 arrays 1D
#   cada uno con 3 reales aleatorios
d = random.rand(2, 4, 3)
print(d)

[[[0.46069412 0.0086092  0.24248074]
  [0.88073955 0.10352765 0.17196375]
  [0.49542079 0.62747938 0.64115075]
  [0.38815409 0.01471381 0.67536626]]

 [[0.80869612 0.59833229 0.77580883]
  [0.86167062 0.77539749 0.39963423]
  [0.05566117 0.70641905 0.34602174]
  [0.62572813 0.6268239  0.96415304]]]


#### Elegir un elemento aleatorio de un array

Dado un array, podemos elegir aleatoriamente un elemento suyo con el método `.choice()`

In [ ]:
x = np.array([1, 2, 3, 4, 5, -5, -4, -3, -2, -1])
print(random.choice(x))

-4


El método `.choice()` también consta del parámetro `size`, con lo cual podemos generar un array aleatorio con los elementos de un array dado:

In [ ]:
print(random.choice(x, size = (3, 6)))

[[-1  5  5  5  4 -2]
 [ 1  2 -4  4 -5 -3]
 [ 2 -2  3 -2  1  5]]


**¡Cuidado!** El método `.choice()` solamente toma como parámetro arrays unidimensionales

Existe otro parámetro del método `.choice()` que nos permite modificar las probabilidades de cada elemento. Éste es el parámetro `p`, al que le tendremos que proporcionar una lista de probabilidades (todos los elementos deben ser menores o iguales a 1 y la suma de todos ellos debe ser 1).

**Observación.** Por defecto, todos los elementos son equiprobables, es decir, tienen la misma probabilidad que es $\frac{1}{n}$, siendo $n$ el número de elementos del array.

In [ ]:
x = np.array([1, 2, 3, 4, 5, -5, -4, -3, -2, -1])
print(random.choice(x,
                    p = [0.2, 0.2, 0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.05, 0.15],
                    size = (2, 6)))

[[-4  4  2  1 -2  2]
 [-1  1 -2  4  1  1]]


En el chunk anterior se ha generado un array 2D con 2 arrays 1D cada uno con 6 elementos, donde las probabilidades para los elementos del array original son:

* Los elementos `1` y `2` tienen probabilidad 0.2 de salir
* El elemento `-1` tiene probabilidad 0.15
* Los elementos `-4` y `-3` tienen probabilidad 0.1 de salir
* Los elementos `3`, `4`, `5`, `6` y `-2` tienen probabilidad 0.05

Todas las probabilidades se encuentran en el intervalo $[0, 1]$ y si las sumamos dan 1.

#### Permutaciones aleatorias

**Permutación.** Una permutación de un array se refiere a la reordenación de sus elementos.

El módulo `random` de `numpy` nos proporciona dos métodos para crear permutaciones aleatorias de un array dado:

* `.shuffle()` modifica el array original
* `.permutation()` que crea una copia


In [ ]:
a = np.array([1, 2, 3, 4])
random.shuffle(a)

print("Array original permutado:", a)

Array original permutado: [4 2 1 3]


In [ ]:
a = np.array([1, 2, 3, 4])
b = random.permutation(a)

print("Array original permutado:", b)
print("Array original:", a)

Array original permutado: [4 1 3 2]
Array original: [1 2 3 4]


### Funciones universales

Las funciones universales son aquellas que operan sobre el objeto ndarray

Podemos comprobar si un método se trata de una función universal con la función `type`. Cuando se trata de una función universal, obtenemos que es de tipo `np.ufunc`

In [ ]:
# Es una función universal
print(type(np.multiply))

<class 'numpy.ufunc'>


In [ ]:
type(np.multiply) == np.ufunc

True

In [ ]:
# No es una función universal
print(type(np.concatenate))

<class 'function'>


In [ ]:
type(np.concatenate) == np.ufunc

False

#### Creando nuestras propias funciones universales

Para crear una función universal propia, primero necesitamos definir una función tal cual aprendimos. A continuación, hay que añadirla a `numpy` con el método `.frompyfunc()`, que tomará por parámetros la función `function`, el número de inputs (arrays), `inputs` y el número de arrays que devuelve, `outputs`:

In [ ]:
def my_sum(x, y):
  return x + y

my_sum = np.frompyfunc(my_sum, 2, 1)
# function = my_sum
# inputs = 2, pues my_sum toma dos arrays
# outputs = 1, pues my_sum devuelve un array, el array suma

a = np.array([1, 0, 7])
b = np.array([-1, 2, 5])
print(my_sum(a, b))

[0 2 12]


In [ ]:
my_sum(np.array([[1,2], [3,4]]), np.array([[1,0], [-1,0]]))

array([[2, 2],
       [2, 4]], dtype=object)

In [ ]:
print(type(my_sum))

<class 'numpy.ufunc'>


#### Aritmética

In [ ]:
a = np.array([12, 0, 7])
b = np.array([8, 2, 5])

El método `.add()` suma arrays elemento a elemento

In [ ]:
print(np.add(a, b))

[20  2 12]


El método `.subtract()` resta arrays elemento a elemento


In [ ]:
print(np.subtract(a, b))

[ 4 -2  2]


El método `.multiply()` multiplica arrays elemento a elemento

In [ ]:
print(np.multiply(a, b))

[96  0 35]


El método `.divide()` divide arrays elemento a elemento

In [ ]:
print(np.divide(a, b))

[1.5 0.  1.4]


El método `.power()` calcula la potencia del primer array elevado al segundo elemento a elemento

In [ ]:
print(np.power(a, b))

[429981696         0     16807]


Tanto el método `.mod()` como el método `.remainder()` calculan el resto de la división entera del primer array entre el segundo, elemento a elemento

In [ ]:
print(np.mod(a, b))
print(np.remainder(a, b))

[4 0 2]
[4 0 2]


El método `.divmod()` devuelve una tupla con 2 arrays, el primero contiene los cocientes y el segundo los restos de las divisiones enteras elemento a elemento

In [ ]:
print(np.divmod(a, b))

(array([1, 0, 1]), array([4, 0, 2]))


El método `.absolute()` devuelve el valor absoluto de cada elemento de un array

In [ ]:
print(np.absolute(np.array([-1, 0, -2, 1, 2])))

[1 0 2 1 2]


#### Redondeando decimales

En `numpy` tenemos 5 formas de redondear los decimales de un número

* `.trunc()` para truncar
* `.fix()` también para truncar
* `.round()` para redondear
* `.floor()` para redondear a la baja
* `.ceil()` para redondear a la alza

In [ ]:
a = np.array([-5.1777, 5.7778, 5.5234])

In [ ]:
print("Si truncamos con .trunc(), obtendremos {}".format(np.trunc(a)))
print("Si truncamos con .fix(), obtendremos {}".format(np.fix(a)))

Si truncamos con .trunc(), obtendremos [-5.  5.  5.]
Si truncamos con .fix(), obtendremos [-5.  5.  5.]


In [ ]:
print("Si rendondeamos con .around(), obtendremos {}".format(np.around(a)))

Si rendondeamos con .around(), obtendremos [-5.  6.  6.]


**Observación.** Como segundo parámetro, podemos indicar a cuántas cifras decimales queremos redondear

In [ ]:
print("Si rendondeamos con .round() a 3 cifras decimales, obtendremos {}".
      format(np.round(a, 3)))

Si rendondeamos con .round() a 3 cifras decimales, obtendremos [-5.178  5.778  5.523]


In [ ]:
print("Si rendondeamos a la baja con .floor(), obtendremos {}".format(np.floor(a)))

Si rendondeamos a la baja con .floor(), obtendremos [-6.  5.  5.]


In [ ]:
print("Si rendondeamos con a la alza .ceil(), obtendremos {}".format(np.ceil(a)))

Si rendondeamos con a la alza .ceil(), obtendremos [-5.  6.  6.]


#### Sumas y Diferencias

Ya concoemos el método `.add()` que dados dos arrays los suma elemento a elemento

In [ ]:
x = np.array([2, 3, 7])
y = np.array([-1, 5, 0])

In [ ]:
print(np.add(x, y))

[1 8 7]


El método `.sum()` nos calcula la suma de los elementos de un array

In [ ]:
print("La suma de los elementos de x es", np.sum(x))
print("La suma de los elementos de y es", np.sum(y))

La suma de los elementos de x es 12
La suma de los elementos de y es 4


**Observación.** Cuando por parámetro pasamos un array multidimensional, volvemos a tener disponible el ya más que conocido parámetro `axis`, para seleccionar sobre qué eje queremos realizar la suma

In [ ]:
z = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
              [[2, 4], [3, 6], [4, 8], [5, 10]],
              [[1, 3], [2, 4], [5, 7], [6, 8]]])

for i in range(z.ndim):
  print("\nLa suma de los elementos de z sobre el axis {}  es\n{}".format(i, np.sum(z, axis = i)))

print("\nLa suma de todos los elementos de z es", np.sum(z))


La suma de los elementos de z sobre el axis 0  es
[[ 4  9]
 [ 8 14]
 [14 21]
 [18 26]]

La suma de los elementos de z sobre el axis 1  es
[[16 20]
 [14 28]
 [14 22]]

La suma de los elementos de z sobre el axis 2  es
[[ 3  7 11 15]
 [ 6  9 12 15]
 [ 4  6 12 14]]

La suma de todos los elementos de z es 114


Para calcular la suma acumulada de los elementos de un array, disponemos del método `.cumsum()`

In [ ]:
print("La suma acumulada de los elementos de x es", np.cumsum(x))
print("La suma acumulada de los elementos de y es", np.cumsum(y))

La suma acumulada de los elementos de x es [ 2  5 12]
La suma acumulada de los elementos de y es [-1  4  4]


**Observación.** Cuando por parámetro pasamos un array multidimensional, volvemos a tener disponible el ya más que conocido parámetro `axis`, para seleccionar sobre qué eje queremos realizar la suma acumulada

In [ ]:
z = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
              [[2, 4], [3, 6], [4, 8], [5, 10]],
              [[1, 3], [2, 4], [5, 7], [6, 8]]])

for i in range(z.ndim):
  print("\nLa suma acumulada de los elementos de z sobre el axis {}  es\n{}".format(i, np.cumsum(z, axis = i)))

print("\nLa suma acumulada de todos los elementos de z es", np.cumsum(z))


La suma acumulada de los elementos de z sobre el axis 0  es
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 3  6]
  [ 6 10]
  [ 9 14]
  [12 18]]

 [[ 4  9]
  [ 8 14]
  [14 21]
  [18 26]]]

La suma acumulada de los elementos de z sobre el axis 1  es
[[[ 1  2]
  [ 4  6]
  [ 9 12]
  [16 20]]

 [[ 2  4]
  [ 5 10]
  [ 9 18]
  [14 28]]

 [[ 1  3]
  [ 3  7]
  [ 8 14]
  [14 22]]]

La suma acumulada de los elementos de z sobre el axis 2  es
[[[ 1  3]
  [ 3  7]
  [ 5 11]
  [ 7 15]]

 [[ 2  6]
  [ 3  9]
  [ 4 12]
  [ 5 15]]

 [[ 1  4]
  [ 2  6]
  [ 5 12]
  [ 6 14]]]

La suma acumulada de todos los elementos de z es [  1   3   6  10  15  21  28  36  38  42  45  51  55  63  68  78  79  82
  84  88  93 100 106 114]


Para calcular las diferencias entre los elementos de un array, disponemos del método `.diff()`

In [ ]:
print("La diferencia de elementos sucesivos de x es", np.diff(x))
print("La diferencia de elementos sucesivos de y es", np.diff(y))

La diferencia de elementos sucesivos de x es [1 4]
La diferencia de elementos sucesivos de y es [ 6 -5]


**Observación.** Cuando por parámetro pasamos un array multidimensional, volvemos a tener disponible el ya más que conocido parámetro `axis`, para seleccionar sobre qué eje queremos realizar la diferencia

In [ ]:
z = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
              [[2, 4], [3, 6], [4, 8], [5, 10]],
              [[1, 3], [2, 4], [5, 7], [6, 8]]])

for i in range(z.ndim):
  print("\nLa diferencia de los elementos sucesivos de z sobre el axis {}  es\n{}".format(i, np.diff(z, axis = i)))


La diferencia de los elementos sucesivos de z sobre el axis 0  es
[[[ 1  2]
  [ 0  2]
  [-1  2]
  [-2  2]]

 [[-1 -1]
  [-1 -2]
  [ 1 -1]
  [ 1 -2]]]

La diferencia de los elementos sucesivos de z sobre el axis 1  es
[[[2 2]
  [2 2]
  [2 2]]

 [[1 2]
  [1 2]
  [1 2]]

 [[1 1]
  [3 3]
  [1 1]]]

La diferencia de los elementos sucesivos de z sobre el axis 2  es
[[[1]
  [1]
  [1]
  [1]]

 [[2]
  [3]
  [4]
  [5]]

 [[2]
  [2]
  [2]
  [2]]]


El parámetro `n` nos permite elegir cuántas veces queremos calcular la diferencia entre los elementos sucesivos de un array:

In [ ]:
print("x =", x)
print("Realizando la diferencia entre sus elementos sucesivos obtenemos", np.diff(x))
print("Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos", np.diff(x, n = 2))

x = [2 3 7]
Realizando la diferencia entre sus elementos sucesivos obtenemos [1 4]
Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos [3]


In [ ]:
print("y =", y)
print("Realizando la diferencia entre sus elementos sucesivos obtenemos", np.diff(y))
print("Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos", np.diff(y, n = 2))

y = [-1  5  0]
Realizando la diferencia entre sus elementos sucesivos obtenemos [ 6 -5]
Realizando 2 veces la diferencia entre sus elementos sucesivos obtenemos [-11]


#### Productos

El método `.prod()` calcula el producto de los elementos de un array

In [ ]:
a = np.array([2, 4, 6, 8])
np.prod(a)

384

**Observación.** Cuando por parámetro pasamos un array multidimensional, volvemos a tener disponible el parámetro `axis`, para seleccionar sobre qué eje queremos realizar el producto de los elementos

In [ ]:
b = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
              [[2, -4], [3, -6], [4, -8], [5, -10]],
              [[-1, 3], [-2, 4], [-5, 7], [-6, 8]]])

for i in range(b.ndim):
  print("\nEl producto de los elementos de b sobre el axis {}  es\n{}".format(i, np.prod(b, axis = i)))

print("\nEl producto de todos los elementos de b es", np.prod(b))


El producto de los elementos de b sobre el axis 0  es
[[  -2  -24]
 [ -18  -96]
 [-100 -336]
 [-210 -640]]

El producto de los elementos de b sobre el axis 1  es
[[ 105  384]
 [ 120 1920]
 [  60  672]]

El producto de los elementos de b sobre el axis 2  es
[[  2  12  30  56]
 [ -8 -18 -32 -50]
 [ -3  -8 -35 -48]]

El producto de todos los elementos de b es 374561832960000


Con el método `.cumprod()` podemos calcular el producto acumulado de un array

In [ ]:
a = np.array([2, 4, 6, 8])
np.cumprod(a)

array([  2,   8,  48, 384])

**Observación.** Cuando por parámetro pasamos un array multidimensional, volvemos a tener disponible el parámetro `axis`, para seleccionar sobre qué eje queremos realizar el producto de los elementos

In [ ]:
b = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]],
              [[2, -4], [3, -6], [4, -8], [5, -10]],
              [[-1, 3], [-2, 4], [-5, 7], [-6, 8]]])

for i in range(b.ndim):
  print("\nEl producto acumulado de los elementos de b sobre el axis {}  es\n{}".format(i, np.cumprod(b, axis = i)))

print("\nEl producto acumulado de todos los elementos de b es", np.cumprod(b))


El producto acumulado de los elementos de b sobre el axis 0  es
[[[   1    2]
  [   3    4]
  [   5    6]
  [   7    8]]

 [[   2   -8]
  [   9  -24]
  [  20  -48]
  [  35  -80]]

 [[  -2  -24]
  [ -18  -96]
  [-100 -336]
  [-210 -640]]]

El producto acumulado de los elementos de b sobre el axis 1  es
[[[   1    2]
  [   3    8]
  [  15   48]
  [ 105  384]]

 [[   2   -4]
  [   6   24]
  [  24 -192]
  [ 120 1920]]

 [[  -1    3]
  [   2   12]
  [ -10   84]
  [  60  672]]]

El producto acumulado de los elementos de b sobre el axis 2  es
[[[  1   2]
  [  3  12]
  [  5  30]
  [  7  56]]

 [[  2  -8]
  [  3 -18]
  [  4 -32]
  [  5 -50]]

 [[ -1  -3]
  [ -2  -8]
  [ -5 -35]
  [ -6 -48]]]

El producto acumulado de todos los elementos de b es [              1               2               6              24
             120             720            5040           40320
           80640         -322560         -967680         5806080
        23224320      -185794560      -928972800      9289

#### Logaritmos

Podemos calcular el logaritmo neperiano de todos los elementos de un array con el método `.log()`

In [ ]:
a = np.array([5, 12, 34, 7, 55])
print(np.log(a))

[1.60943791 2.48490665 3.52636052 1.94591015 4.00733319]


`numpy` no ofrece ningún método que calcule logartimos en cualquier otra base que no sea `e`. Por eso, la creamos nosotros a partir del método `math.log()`

In [ ]:
from math import log

nplog = np.frompyfunc(log, 2, 1)
print(nplog(np.array([100, 1000, 50, 500]), 10))

[2.0 2.9999999999999996 1.6989700043360185 2.6989700043360183]


#### MCM y MCD

Podemos calcular el Mínimo Común Múltiplo de los elementos de un array con el método `.lcm.reduce()`

In [ ]:
a = np.array([2, 3, 5, 12])
np.lcm.reduce(a)

60

Podemos calcular el Máximo Común Divisor de los elementos de un array con el método `.gcd.reduce()`

In [ ]:
b = np.array([15, 12, 27])
np.gcd.reduce(b)

3

#### Trigonometría

En `numpy` el número $\pi$ se obtiene con `np.pi`.

En `numpy` disponemos de los métodos:

* `.sin()`
* `.cos()`
* `.tan()`

para calcular el seno, coseno y tangente de los elementos de un array (los valores se consideran en radianes)

* `.deg2rad()`
* `.rad2deg()`

para calcular conversión de ángulos a radianes y de radianes a ángulos respectivamente

* `.arcsin()`
* `.arccos()`
* `.arctan()`

para calcular el arcoseno, arcocoseno y arcotangente y hallar ángulos (el resultado es devuelto en radianes)

#### Funciones hiperbólicas

En `numpy` disponemos de los métodos:

* `.sinh()`
* `.cosh()`
* `.tanh()`

para calcular el seno, coseno y tangente hiperbólicos de los elementos de un array (los valores se consideran en radianes)

* `.arcsinh()`
* `.arccosh()`
* `.arctanh()`

para calcular el arcoseno, arcocoseno y arcotangente hiperbólicos y hallar ángulos (el resultado es devuelto en radianes)

#### Conjuntos en `numpy`

Para crear un conjunto a partir de un array, usamos el método `.unique()`:  

In [ ]:
a = np.array([1, 2, -1, 1, 5, 6, 2, 4, -1, 2])
set_a = np.unique(a)
print(set_a)

[-1  1  2  4  5  6]


Para hallar la unión entre dos arrays 1D, usamos el método `.union1d()`

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([-2, -1, 0, 1])
print(np.union1d(x, y))

[-2 -1  0  1  2  3  4]


Para hallar la intersección entre dos arrays 1D, usamos el método `.intersect1d()`

In [ ]:
print(np.intersect1d(x, y))

[1]


Para hallar la diferencia entre dos arrays 1D, disponemos del método `.setdiff1d()`

In [ ]:
print(np.setdiff1d(x, y))
print(np.setdiff1d(y, x))

[2 3 4]
[-2 -1  0]


Para hallar la diferencia simétrica entre dos arrays 1D, usamos el método `.setxor1d()`

In [ ]:
print(np.setxor1d(x, y))

[-2 -1  0  2  3  4]
