# Clase5 : Numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

## Creación de arrays

In [ ]:
# Crear un array NumPy a partir de una lista
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
# Crear un array NumPy de ceros
arr_zeros = np.zeros(5)
arr_zeros

array([0., 0., 0., 0., 0.])

In [ ]:
# Crear un array NumPy de unos
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

In [ ]:
# Crear un array NumPy de números equiespaciados
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

arr_linspace = np.linspace(0, 1, 10)  # 10 números entre 0 y 1
arr_linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
# Crear un array NumPy de números equiespaciados
# numpy.arange(start, stop, step, dtype=None)

arr_arange = np.arange(0,10,2)  # números entre 0 y 10 con espacio de 2
arr_arange

array([0, 2, 4, 6, 8])

In [ ]:
# Crear un array NumPy con números aleatorios
arr_random = np.random.rand(5)  # 5 números aleatorios entre 0 y 1
arr_random

array([0.29791806, 0.59171509, 0.44101208, 0.29714174, 0.63131699])

## Operaciones básicas

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
# Suma de arrays
suma = arr1 + arr2
suma

array([5, 7, 9])

In [ ]:
# Resta de arrays
resta = arr1 - arr2
resta

array([-3, -3, -3])

In [ ]:
# Producto elemento por elemento
producto = arr1 * arr2
producto

array([ 4, 10, 18])

In [ ]:
# Producto punto (dot product)
dot_product = np.dot(arr1, arr2)
dot_product

32

In [ ]:
# Transposición de un array
transpuesto = arr1.T
transpuesto

array([1, 2, 3])

## Manipulación

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# Obtener la forma (shape) de un array
arr_shape = arr.shape
arr_shape # (filas,columnas)

(3, 3)

In [ ]:
arr_shape[0]

3

In [ ]:
# Cambiar la forma de un array
arr_reshape = arr.reshape(3, 3)
arr_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Indexación y segmentación de arrays
subarray = arr[0:2, 1:3]
subarray

array([[2, 3],
       [5, 6]])

In [ ]:
arr[2,1]

8

In [ ]:
arr[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
# Obtener el valor máximo y mínimo de un array
max_value = np.max(arr)
min_value = np.min(arr)
min_value,max_value

(1, 9)

## Funciones matemáticas

In [ ]:
arr = np.array([1, 2, 3])

In [ ]:
seno = np.sin(arr)
seno

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
coseno = np.cos(arr)
coseno

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
exponencial = np.exp(arr)
exponencial

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
logaritmo = np.log(arr)
np.round(logaritmo,3)

array([0.   , 0.693, 1.099])

In [ ]:
redondeo = np.round([1.2, 2.7, 3.5],2)
redondeo

array([1.2, 2.7, 3.5])

## Álgebra lineal

In [ ]:
vector = np.array([5, 6])
vector

array([5, 6])

In [ ]:
matriz = np.array([[1, 2], [3, 4]])
matriz

array([[1, 2],
       [3, 4]])

In [ ]:
producto_matriz = np.dot(matriz, vector)
producto_matriz

array([17, 39])

In [ ]:
determinante = np.linalg.det(matriz)
determinante

-2.0000000000000004

In [ ]:
inversa = np.linalg.inv(matriz)
inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
traspuesta = np.transpose(matriz)
traspuesta

array([[1, 3],
       [2, 4]])

In [ ]:
valores_propios,vectores_propios=np.linalg.eig(matriz)

In [ ]:
vectores_propios

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [ ]:
valores_propios

array([-0.37228132,  5.37228132])